# Generated by Django 3.0.2 on 2020-06-03 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goodsNo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('goodsName', models.CharField(max_length=50)),
                ('goodsIdx_x', models.FloatField()),
                ('goodsIdx_y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('robotNo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('robotState', models.IntegerField()),
                ('robotIdx_x', models.FloatField()),
                ('robotIdx_y', models.FloatField()),
                ('robotPower', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomNo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('roomIdx_x', models.FloatField()),
                ('roomIdx_y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('insNo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('insType', models.IntegerField()),
                ('insGoodsNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.Goods')),
                ('insRoomNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.Room')),
            ],
        ),
    ]
